import {COUNTRY_PREFIXES,PUBLIC_TIMEZONE_LABEL} from './contracts.js';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(path,options={})=>{const {headers:extraHeaders,...rest}=options;const r=await fetch(path,{credentials:'same-origin',...rest,headers:{Accept:'application/json','Content-Type':'application/json',...(extraHeaders||{})}});let b=null;try{b=await r.json();}catch{}if(!r.ok)throw Error(b?.error||b?.message||`Error de conexión (${r.status})`);return b;};
const fmt=iso=>new Intl.DateTimeFormat('es-MX',{timeZone:'America/Mexico_City',dateStyle:'full',timeStyle:'short'}).format(new Date(iso))+' · '+PUBLIC_TIMEZONE_LABEL;
const day=iso=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Mexico_City',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(iso));
let slots=[],request,token,key;
function form(){const dates=[...new Set(slots.map(s=>day(s.start_at)))],countries=COUNTRY_PREFIXES.map(([c,n,p])=>`<option value="${esc(c)}" data-prefix="${esc(p)}" ${c==='MX'?'selected':''}>${esc(n)} ${esc(p)}</option>`).join(''),groups=dates.map(d=>`<div class="slot-date"><h3>${esc(d)}</h3><div class="slot-grid">${slots.filter(s=>day(s.start_at)===d).map(s=>`<label class="slot-option"><input type="radio" name="slot_id" value="${esc(s.slot_id)}" required><span>${esc(fmt(s.start_at))}</span></label>`).join('')}</div></div>`).join('');$('#public-app').innerHTML=`<div class="page"><div class="page-head"><div><p class="eyebrow">UMBRAL · DISPONIBILIDAD</p><h1>Solicitar una cita</h1><p>Elige un horario disponible y deja tu WhatsApp. La confirmación requiere revisión humana.</p></div></div><section class="panel"><p class="timezone-alert">Todos los horarios se muestran en hora de Ciudad de México. Si estás en otro país, considera la diferencia horaria antes de solicitar tu cita.</p><form id="public-booking-form">${groups}<h2>WhatsApp</h2><div class="phone-fields"><label>País / prefijo<select name="country_code" id="public-country" required>${countries}</select></label><label>Prefijo<input name="calling_code" value="+52" readonly required></label><label>Número de WhatsApp<input name="whatsapp_number" inputmode="tel" required></label></div><p class="public-boundary">El país sólo define el prefijo. No cambia las fechas ni las horas mostradas.</p><h2>Datos de la solicitud</h2><label>Nombre completo<input name="requester_name" autocomplete="name" maxlength="120" required></label><label>Asunto o motivo breve<input name="request_subject" maxlength="200" placeholder="Ej. Seguimiento operadores" required></label><button class="primary wide" type="submit" ${slots.length?'':'disabled'}>SOLICITAR CITA</button><p class="form-error" role="alert"></p></form><div id="public-summary">Selecciona un horario. Se mostrará siempre en ${PUBLIC_TIMEZONE_LABEL}.</div></section></div>`;}
function success(){ $('#public-app').innerHTML=`<div class="page"><section class="panel booking-success"><p class="request-state">SOLICITUD RECIBIDA / PENDIENTE DE REVISIÓN</p><h1>Tu solicitud quedó registrada.</h1><h2>${esc(fmt(request.requested_start_at))}</h2><p>WhatsApp normalizado: <b>${esc(request.whatsapp_e164)}</b></p><form id="public-email-form"><label>¿A qué correo quieres que enviemos la confirmación?<input type="email" name="email" required></label><button class="primary" type="submit">Guardar correo</button><p class="form-error" role="alert"></p></form><p class="public-boundary">BOOKING REQUEST ≠ CONFIRMED APPOINTMENT</p></section></div>`;}
async function load(){try{const b=await api('/api/public/availability');slots=b.slots||[];form();}catch(e){$('#public-notice').textContent=e.message;$('#public-app').innerHTML='<section class="panel booking-error"><h1>Disponibilidad no disponible</h1><p>La fuente remota no está disponible. No se muestran horarios de demostración.</p></section>';}};
document.addEventListener('change',e=>{if(e.target.id==='public-country'){const p=e.target.form.elements.calling_code;p.value=e.target.selectedOptions[0].dataset.prefix||'';p.readOnly=e.target.value!=='OTHER';}if(e.target.name==='slot_id'){const s=slots.find(x=>x.slot_id===e.target.value);$('#public-summary').innerHTML=s?`<b>Horario seleccionado</b><p>${esc(fmt(s.start_at))}</p>`:'';}});
document.addEventListener('submit',async e=>{const f=e.target;if(f.id==='public-booking-form'){e.preventDefault();key=key||crypto.randomUUID();f.querySelector('button[type=submit]').disabled=true;try{request=await api('/api/public/requests',{method:'POST',headers:{'Idempotency-Key':key},body:JSON.stringify(Object.fromEntries(new FormData(f)))});token=request.request_token;success();}catch(err){f.querySelector('.form-error').textContent=err.message;f.querySelector('button[type=submit]').disabled=false;}}else if(f.id==='public-email-form'){e.preventDefault();try{await api(`/api/public/requests/${encodeURIComponent(request.request_id)}/email`,{method:'PUT',headers:{Authorization:`Bearer ${token}`},body:JSON.stringify({email:new FormData(f).get('email')})});f.innerHTML='<p class="public-boundary">Correo registrado para notificaciones.</p>';}catch(err){f.querySelector('.form-error').textContent=err.message;}}});load();